const Footer = () => (
  <footer className="sticky-footer bg-white">
    <div className="container my-auto">
      <div className="copyright text-center my-auto text-primary">
        <span style={{ color: '#365F9F' }}>
          All data is generated by AI - For Portfolio Use Only.
        </span>
      </div>
    </div>
  </footer>
)

export default Footer
